const styles = {
  container: "mx-auto flex min-h-screen max-w-[600px] flex-col bg-white font-[var(--font-family)]",
  topBar: "sticky top-0 z-10 flex items-center gap-4 bg-white px-5 py-4 border-b-2 border-[#f0f0f0]",
  closeButton: "flex items-center bg-transparent p-0 text-2xl text-[#a0aab5] hover:text-[#526577]",
  progressContainer: "h-4 flex-1 overflow-hidden rounded-[10px] bg-[#e5e5e5] ltr",
  progressFill: "h-full rounded-[10px] bg-[#58cc02] transition-all duration-300",
  storyToggleBtn: "flex items-center gap-1.5 rounded-xl border-2 border-[#1cb0f6] bg-white px-3 py-1.5 text-[0.9rem] font-bold text-[#1cb0f6] hover:bg-[#ddf4ff]",
  practiceCard: "flex flex-1 flex-col pb-[120px]",
  cardBody: "flex flex-1 flex-col items-center justify-center p-5",
  instructionTitle: "mb-5 w-full text-right text-2xl font-extrabold text-[#3c3c3c]",
  questionText: "mb-[30px] text-center text-[1.8rem] font-bold leading-relaxed text-[#3c3c3c]",
  optionsGrid: "grid w-full grid-cols-2 gap-4 ltr",
  optionCard: "cursor-pointer rounded-2xl border-2 border-b-4 border-[#e5e5e5] bg-white p-4 text-center text-[1.2rem] font-bold text-[#3c3c3c] hover:bg-[#f7f7f7] disabled:cursor-not-allowed",
  selected: "border-[#1cb0f6] bg-[#ddf4ff] text-[#1cb0f6]",
  correct: "border-[#58cc02] border-b-[#58a700] bg-[#d7ffb8] text-[#58a700]",
  wrong: "border-[#ff4b4b] border-b-[#ea2b2b] bg-[#ffdfe0] text-[#ea2b2b]",
  writeInput: "w-full rounded-2xl border-2 border-[#e5e5e5] bg-[#f7f7f7] p-[18px] text-center text-[1.3rem] text-[#3c3c3c] outline-none focus:border-[#1cb0f6] focus:bg-white",
  tfContainer: "flex w-full gap-4 ltr",
  tfBtn: "flex-1 cursor-pointer rounded-2xl border-2 border-b-4 border-[#e5e5e5] bg-white p-5 text-[1.2rem] font-bold text-[#3c3c3c]",
  footerArea: "fixed bottom-0 left-0 right-0 z-[100] flex justify-center border-t-2 border-[#e5e5e5] bg-white p-5",
  footerContent: "flex w-full max-w-[600px] items-center justify-between",
  feedbackMessage: "flex items-center gap-4",
  feedbackIcon: "flex h-[50px] w-[50px] items-center justify-center rounded-full bg-white text-[1.8rem]",
  feedbackText: "",
  actionButton: "min-w-[120px] cursor-pointer rounded-2xl border-none border-b-4 border-b-[#58a700] bg-[#58cc02] px-6 py-3.5 text-[1.2rem] font-extrabold text-white disabled:cursor-not-allowed disabled:border-b-[#afafaf] disabled:bg-[#e5e5e5] disabled:text-[#afafaf]",
  wrongState: "border-b-[#ea2b2b] bg-[#ff4b4b]",
  modalOverlay: "fixed inset-0 z-[200] flex items-center justify-center bg-[rgba(15,23,42,0.5)] p-5 backdrop-blur-[8px]",
  storyModal: "flex max-h-[85vh] w-full max-w-[480px] flex-col overflow-hidden rounded-3xl border border-black/5 bg-white shadow-[0_20px_40px_rgba(0,0,0,0.15)]",
  modalHeader: "flex items-center justify-between border-b border-[#f1f5f9] bg-white px-6 py-5",
  closeModalBtn: "flex h-9 w-9 items-center justify-center rounded-full bg-[#f8fafc] text-[1.1rem] text-[#64748b] hover:bg-[#fee2e2] hover:text-[#ef4444]",
  modalBody: "flex flex-col gap-5 overflow-y-auto p-6",
  storyImage: "h-[180px] w-full rounded-2xl object-cover shadow-[0_4px_12px_rgba(0,0,0,0.05)]",
  audioContainer: "flex flex-col gap-3 rounded-[20px] border border-[#bae6fd] bg-gradient-to-br from-[#f0f9ff] to-[#e0f2fe] px-5 py-4 shadow-[0_4px_15px_rgba(14,165,233,0.08)]",
  audioLabel: "flex items-center gap-2 text-base font-extrabold text-[#0284c7]",
  audioPlayer: "h-11 w-full",
  storyText: "rounded-2xl border-l-4 border-l-[#3b82f6] bg-[#f8fafc] p-5 text-left text-[1.1rem] leading-[1.7] text-[#334155] ltr",
  customPlayer: "flex w-full items-center gap-4 rounded-[50px] border-2 border-[#e2e8f0] bg-white px-5 py-2.5 shadow-[0_4px_10px_rgba(0,0,0,0.03)]",
  playBtn: "flex h-[45px] w-[45px] flex-shrink-0 items-center justify-center rounded-full bg-[#1cb0f6] text-[1.2rem] text-white shadow-[0_4px_10px_rgba(28,176,246,0.3)] hover:scale-105 hover:bg-[#1899d6]",
  progressBar: "h-2 flex-1 cursor-pointer appearance-none rounded-[10px] bg-[#e2e8f0]",
  shake: "animate-pulse border-[#ff4b4b] bg-[#ffdfe0]",
  progressText: "mt-2 flex justify-between text-sm text-[#666]",
  progressBarWrap: "overflow-hidden rounded-lg bg-[#e5e5e5]"
};

export default styles;
