const styles = {
  container: "mx-auto min-h-[80vh] max-w-[1000px] px-6 py-12",
  loader: "flex justify-center font-black",
  headerSection: "mb-12 text-center",
  badge: "mb-2.5 inline-block rounded-full border border-[#fce7f3] bg-[#fdf2f8] px-3.5 py-1.5 font-bold text-[#db2777]",
  badgeAdmin: "mb-2.5 inline-block rounded-full bg-[#333] px-3.5 py-1.5 font-bold text-white",
  mainTitle: "mb-1 text-[2.5rem] font-black text-[var(--dark-color)]",
  subTitle: "text-[1.1rem] text-[#666]",
  marketingContainer: "flex flex-col gap-16",
  visualSection: "grid items-center gap-10 md:grid-cols-2",
  imageFrame: "relative overflow-hidden rounded-[20px] border-4 border-white shadow-[0_20px_40px_rgba(0,0,0,0.1)] transition duration-300 hover:scale-[1.02]",
  mockupImage: "block h-auto w-full",
  floatingTag: "absolute right-4 top-4 rounded-[20px] bg-[rgba(255,0,0,0.9)] px-3 py-1 text-xs font-bold text-white shadow-[0_4px_10px_rgba(0,0,0,0.2)]",
  visualText: "",
  featuresGrid: "grid gap-6 [grid-template-columns:repeat(auto-fit,minmax(250px,1fr))]",
  featureCard: "rounded-[20px] border border-[#f0f0f0] bg-white p-[30px] text-center transition duration-300 hover:-translate-y-2 hover:border-[var(--primary-color)] hover:shadow-[0_15px_30px_rgba(0,0,0,0.05)]",
  iconBox: "mx-auto mb-5 flex h-[60px] w-[60px] items-center justify-center rounded-full text-2xl",
  prototypeSection: "flex flex-col gap-5",
  prototypeHeader: "text-center",
  prototypeGrid: "grid gap-4 [grid-template-columns:repeat(auto-fit,minmax(170px,1fr))]",
  prototypeCard: "rounded-xl border border-[#e5e7eb] bg-white p-2.5 shadow-[0_10px_20px_rgba(0,0,0,0.05)]",
  prototypeImage: "block w-full rounded-lg object-cover [aspect-ratio:210/297]",
  ctaBox: "rounded-3xl bg-gradient-to-br from-[var(--secondary-color)] to-[#ff9100] p-10 text-center text-white shadow-[0_20px_50px_rgba(255,123,0,0.3)]",
  ctaContent: "",
  upgradeBtn: "inline-flex items-center gap-2.5 rounded-full bg-white px-10 py-4 text-[1.2rem] font-extrabold text-[var(--secondary-color)] no-underline shadow-[0_10px_20px_rgba(0,0,0,0.1)] transition hover:scale-105",
  dashboardContainer: "flex flex-col gap-8",
  welcomeCard: "flex items-center justify-between gap-4 rounded-[20px] border border-[#f0f0f0] bg-white p-[30px] shadow-[0_5px_20px_rgba(0,0,0,0.03)] max-md:flex-col max-md:text-center",
  welcomeText: "",
  statusBadge: "flex items-center gap-2 rounded-full border border-[#dcfce7] bg-[#f0fdf4] px-4 py-2 font-bold text-[#166534]",
  dashboardGrid: "grid gap-6 [grid-template-columns:repeat(auto-fit,minmax(300px,1fr))]",
  infoCard: "flex h-full flex-col rounded-[20px] border border-[#e5e7eb] bg-white p-6",
  actionCard: "flex h-full flex-col rounded-[20px] border border-[#dcfce7] bg-[#f0fdf4] p-6",
  cardHeader: "mb-5 flex items-center gap-3 border-b border-black/5 pb-4",
  cardIcon: "text-2xl",
  cardBody: "flex flex-1 flex-col gap-4",
  highlightText: "text-[1.1rem] text-[#333]",
  topicBox: "rounded-xl border-l-4 border-l-[var(--primary-color)] bg-[#f8fafc] p-4",
  note: "mt-auto text-[0.85rem] text-[#666]",
  rulesBox: "mb-5 rounded-xl border border-[#ffeeba] bg-[#fff9e6] p-4 text-right",
  rulesList: "m-0 list-none p-0",
  whatsappFullBtn: "mt-auto w-full rounded-xl bg-[#25D366] p-4 text-base font-bold text-white transition hover:-translate-y-1 hover:shadow-[0_5px_15px_rgba(37,211,102,0.3)]",
  secureBadge: "mt-2.5 flex items-center justify-center gap-1.5 text-center text-xs text-[#166534] opacity-80",
  adminStatsBar: "grid gap-5 [grid-template-columns:repeat(auto-fit,minmax(200px,1fr))]",
  statItem: "rounded-2xl border border-[#eee] bg-white p-5 text-center",
  statLabel: "mb-1 block text-[0.9rem] text-[#888]",
  statNumber: "text-[1.8rem] font-black text-[#333]",
  adminLinks: "flex flex-col gap-2.5",
  adminActionBtn: "cursor-pointer rounded-lg border-none bg-[#f3f4f6] p-3 text-right font-semibold text-[#333] transition hover:bg-[#e5e7eb]",
  groupsList: "m-0 list-none p-0",
  statusDot: "inline-block h-2.5 w-2.5 rounded-full"
};

export default styles;
