// --- THEME 1: SURVIVAL BASICS (80 Words) ---
export const theme_1_words = [
  // --- Pronouns (الضمائر) ---
  { id: "word:101", en: "I", darija: "أنا" },
  { id: "word:102", en: "You", darija: "أنتَ/أنتِ" },
  { id: "word:103", en: "He", darija: "هو" },
  { id: "word:104", en: "She", darija: "هي" },
  { id: "word:105", en: "We", darija: "حنا" },
  { id: "word:106", en: "They", darija: "هما" },
  { id: "word:107", en: "It", darija: "لغير العاقل" },
  { id: "word:108", en: "My", darija: "ديالي" },
  { id: "word:109", en: "Your", darija: "ديالك" },
  { id: "word:110", en: "His", darija: "ديالو" },
  { id: "word:111", en: "Her", darija: "ديالها" },
  { id: "word:112", en: "Our", darija: "ديالنا" },
  { id: "word:113", en: "Their", darija: "ديالهم" },

  // --- Greetings & Politeness (التحيات والأدب) ---
  { id: "word:114", en: "Hello", darija: "سلام" },
  { id: "word:115", en: "Goodbye", darija: "بسلامة" },
  { id: "word:116", en: "Good morning", darija: "صباح الخير" },
  { id: "word:117", en: "Good night", darija: "تصبح على خير" },
  { id: "word:118", en: "Please", darija: "عفاك" },
  { id: "word:119", en: "Thank you", darija: "شكراً" },
  { id: "word:120", en: "Sorry", darija: "سمح ليا" },
  { id: "word:121", en: "Excuse me", darija: "معذرة" },
  { id: "word:122", en: "Yes", darija: "أه / نعم" },
  { id: "word:123", en: "No", darija: "لا" },
  { id: "word:124", en: "Okay", darija: "واخا" },
  { id: "word:125", en: "Maybe", darija: "يمكن" },
  { id: "word:126", en: "Problem", darija: "مشكل" },
  { id: "word:127", en: "No problem", darija: "ماشي مشكل" },
  { id: "word:128", en: "Help", darija: "عاوني" },
  { id: "word:129", en: "Welcome", darija: "مرحباً" },

  // --- Question Words (أدوات السؤال) ---
  { id: "word:130", en: "What", darija: "شنو" },
  { id: "word:131", en: "Where", darija: "فين" },
  { id: "word:132", en: "When", darija: "فوقاش" },
  { id: "word:133", en: "Who", darija: "شكون" },
  { id: "word:134", en: "Why", darija: "علاش" },
  { id: "word:135", en: "How", darija: "كيفاش" },
  { id: "word:136", en: "How much", darija: "شحال (ثمن)" },
  { id: "word:137", en: "How many", darija: "شحال (عدد)" },

  // --- Adjectives & Directions (صفات واتجاهات) ---
  { id: "word:138", en: "Here", darija: "هنا" },
  { id: "word:139", en: "There", darija: "لهيه" },
  { id: "word:140", en: "This", darija: "هذا" },
  { id: "word:141", en: "That", darija: "هداك" },
  { id: "word:142", en: "Good", darija: "مزيان" },
  { id: "word:143", en: "Bad", darija: "خايب" },
  { id: "word:144", en: "Big", darija: "كبير" },
  { id: "word:145", en: "Small", darija: "صغير" },
  { id: "word:146", en: "Hot", darija: "سخون" },
  { id: "word:147", en: "Cold", darija: "بارد" },
  { id: "word:148", en: "Open", darija: "محلول" },
  { id: "word:149", en: "Closed", darija: "مسدود" },
  { id: "word:150", en: "Left", darija: "يسار" },
  { id: "word:151", en: "Right", darija: "يمين" },
  { id: "word:152", en: "Up", darija: "فوق" },
  { id: "word:153", en: "Down", darija: "تحت" },
  { id: "word:154", en: "Near", darija: "قريب" },
  { id: "word:155", en: "Far", darija: "بعيد" },

  // --- Time & Numbers (الوقت والأرقام) ---
  { id: "word:156", en: "Now", darija: "دابا" },
  { id: "word:157", en: "Later", darija: "من بعد" },
  { id: "word:158", en: "Today", darija: "اليوم" },
  { id: "word:159", en: "Tomorrow", darija: "غدا" },
  { id: "word:160", en: "Yesterday", darija: "البارح" },
  { id: "word:161", en: "One", darija: "1" },
  { id: "word:162", en: "Two", darija: "2" },
  { id: "word:163", en: "Three", darija: "3" },
  { id: "word:164", en: "Four", darija: "4" },
  { id: "word:165", en: "Five", darija: "5" },
  { id: "word:166", en: "Six", darija: "6" },
  { id: "word:167", en: "Seven", darija: "7" },
  { id: "word:168", en: "Eight", darija: "8" },
  { id: "word:169", en: "Nine", darija: "9" },
  { id: "word:170", en: "Ten", darija: "10" },
  { id: "word:171", en: "Zero", darija: "0" },
  { id: "word:172", en: "Hundred", darija: "100" },

  // --- Verbs (أفعال الفهم) ---
  { id: "word:173", en: "Speak", darija: "هضر" },
  { id: "word:174", en: "Understand", darija: "فهم" },
  { id: "word:175", en: "Know", darija: "عرف" },
  { id: "word:176", en: "Want", darija: "بغى" },
  { id: "word:177", en: "Need", darija: "احتاج" },
  { id: "word:178", en: "Like", darija: "عجب" },
  { id: "word:179", en: "See", darija: "شاف" },
  { id: "word:180", en: "Hear", darija: "سمع" }
];

// --- THEME 2: DAILY ROUTINE (100 Words) ---
export const theme_2_words = [
  // --- Routine Verbs (أفعال الروتين) ---
  { id: "word:201", en: "Wake up", darija: "فاق" },
  { id: "word:202", en: "Get up", darija: "ناض" },
  { id: "word:203", en: "Sleep", darija: "نعس" },
  { id: "word:204", en: "Wash", darija: "غسل" },
  { id: "word:205", en: "Brush", darija: "حك / مشط" },
  { id: "word:206", en: "Shower", darija: "دوش" },
  { id: "word:207", en: "Dress", darija: "لبس" },
  { id: "word:208", en: "Eat", darija: "كلا" },
  { id: "word:209", en: "Drink", darija: "شرب" },
  { id: "word:210", en: "Cook", darija: "طيب" },
  { id: "word:211", en: "Clean", darija: "نقى / نظف" },
  { id: "word:212", en: "Work", darija: "خدم" },
  { id: "word:213", en: "Study", darija: "قرا (دراسة)" },
  { id: "word:214", en: "Read", darija: "قرا (كتاب)" },
  { id: "word:215", en: "Write", darija: "كتب" },
  { id: "word:216", en: "Listen", darija: "سمع / تصنت" },
  { id: "word:217", en: "Watch", darija: "تفرج" },
  { id: "word:218", en: "Play", darija: "لعب" },
  { id: "word:219", en: "Rest", darija: "رتاح" },
  { id: "word:220", en: "Walk", darija: "تمشى" },
  { id: "word:221", en: "Run", darija: "جرى" },
  { id: "word:222", en: "Drive", darija: "صاغ" },
  { id: "word:223", en: "Ride", darija: "ركب" },
  { id: "word:224", en: "Buy", darija: "شرا" },
  { id: "word:225", en: "Pay", darija: "خلص" },
  { id: "word:226", en: "Wait", darija: "تسنى" },

  // --- Daily Objects (أشياء يومية) ---
  { id: "word:227", en: "Alarm", darija: "منبه / فيقة" },
  { id: "word:228", en: "Bed", darija: "ناموسية" },
  { id: "word:229", en: "Soap", darija: "صابون" },
  { id: "word:230", en: "Towel", darija: "فوطة" },
  { id: "word:231", en: "Toothbrush", darija: "شيتة السنان" },
  { id: "word:232", en: "Clothes", darija: "حوايج" },
  { id: "word:233", en: "Shoes", darija: "صباط" },
  { id: "word:234", en: "Bag", darija: "شكارة" },
  { id: "word:235", en: "Phone", darija: "تليفون" },
  { id: "word:236", en: "Key", darija: "ساروت" },
  { id: "word:237", en: "Wallet", darija: "بسطام" },
  { id: "word:238", en: "Money", darija: "فلوس" },
  { id: "word:239", en: "Book", darija: "كتاب" },
  { id: "word:240", en: "Pen", darija: "ستيلو" },
  { id: "word:241", en: "Computer", darija: "بيسي" },
  { id: "word:242", en: "TV", darija: "تلفزة" },
  { id: "word:243", en: "Breakfast", darija: "فطور" },
  { id: "word:244", en: "Lunch", darija: "غداء" },
  { id: "word:245", en: "Dinner", darija: "عشاء" },
  { id: "word:246", en: "Tea", darija: "أتاي" },
  { id: "word:247", en: "Coffee", darija: "قهوة" },
  { id: "word:248", en: "Water", darija: "ماء" },
  { id: "word:249", en: "Bread", darija: "خبز" },

  // --- Places & Time (الأماكن والوقت) ---
  { id: "word:250", en: "House", darija: "دار" },
  { id: "word:251", en: "Room", darija: "بيت" },
  { id: "word:252", en: "Kitchen", darija: "كوزينة" },
  { id: "word:253", en: "Bathroom", darija: "دوش / طواليت" },
  { id: "word:254", en: "Bedroom", darija: "بيت النعاس" },
  { id: "word:255", en: "Door", darija: "باب" },
  { id: "word:256", en: "Window", darija: "شرجم" },
  { id: "word:257", en: "Office", darija: "بيرو" },
  { id: "word:258", en: "School", darija: "مدرسة" },
  { id: "word:259", en: "Car", darija: "طموبيل" },
  { id: "word:260", en: "Bus", darija: "طوبيس" },
  { id: "word:261", en: "Taxi", darija: "طاكسي" },
  { id: "word:262", en: "Morning", darija: "صباح" },
  { id: "word:263", en: "Afternoon", darija: "عشية" },
  { id: "word:264", en: "Night", darija: "ليل" },
  { id: "word:265", en: "Hour", darija: "ساعة" },
  { id: "word:266", en: "Minute", darija: "دقيقة" },
  { id: "word:267", en: "Early", darija: "بكيري" },
  { id: "word:268", en: "Late", darija: "معطل" },
  { id: "word:269", en: "Fast", darija: "زربة / دغيا" },
  { id: "word:270", en: "Slow", darija: "تقيل / بشوية" },
  { id: "word:271", en: "Every day", darija: "كل نهار" },
  { id: "word:272", en: "Always", darija: "ديما" },
  { id: "word:273", en: "Usually", darija: "غالباً" },
  { id: "word:274", en: "Sometimes", darija: "مرة مرة" },
  { id: "word:275", en: "Never", darija: "أبداً / عمرني" },
  { id: "word:276", en: "Week", darija: "سيمانة" },
  { id: "word:277", en: "Month", darija: "شهر" },
  { id: "word:278", en: "Year", darija: "عام" },
  { id: "word:279", en: "Start", darija: "بدا" },
  { id: "word:280", en: "Finish", darija: "سلا" },
  { id: "word:281", en: "Busy", darija: "مشغول" },
  { id: "word:282", en: "Free", darija: "مسالي" },
  { id: "word:283", en: "Tired", darija: "عيان" },
  { id: "word:284", en: "Hungry", darija: "جيعان" },
  { id: "word:285", en: "Thirsty", darija: "عطشان" },
  { id: "word:286", en: "Full", darija: "شبعان / عامر" },
  { id: "word:287", en: "Ready", darija: "واجد" }
];

// --- THEME 3: FAMILY & PEOPLE (100 Words) ---
export const theme_3_words = [
  // --- Family Members (العائلة) ---
  { id: "word:301", en: "Family", darija: "عائلة" },
  { id: "word:302", en: "Parents", darija: "والدين" },
  { id: "word:303", en: "Father", darija: "أب / واليد" },
  { id: "word:304", en: "Dad", darija: "بابا" },
  { id: "word:305", en: "Mother", darija: "أم / واليدة" },
  { id: "word:306", en: "Mom", darija: "ماما" },
  { id: "word:307", en: "Husband", darija: "زوج / راجل" },
  { id: "word:308", en: "Wife", darija: "زوجة / مرى" },
  { id: "word:309", en: "Son", darija: "ولد / ابن" },
  { id: "word:310", en: "Daughter", darija: "بنت / ابنة" },
  { id: "word:311", en: "Brother", darija: "خو" },
  { id: "word:312", en: "Sister", darija: "أخت" },
  { id: "word:313", en: "Grandfather", darija: "جد" },
  { id: "word:314", en: "Grandmother", darija: "جدة" },
  { id: "word:315", en: "Uncle", darija: "عم / خال" },
  { id: "word:316", en: "Aunt", darija: "عمة / خالة" },
  { id: "word:317", en: "Cousin", darija: "ولد العم/الخال" },
  { id: "word:318", en: "Baby", darija: "بيبي" },
  { id: "word:319", en: "Child", darija: "طفل" },
  { id: "word:320", en: "Kid", darija: "دري صغير" },
  { id: "word:321", en: "Children", darija: "دراري / أطفال" },
  { id: "word:322", en: "Twins", darija: "توأم" },

  // --- People & Roles (الناس والمهن) ---
  { id: "word:323", en: "Person", darija: "شخص" },
  { id: "word:324", en: "People", darija: "ناس" },
  { id: "word:325", en: "Man", darija: "راجل" },
  { id: "word:326", en: "Woman", darija: "مرأة" },
  { id: "word:327", en: "Boy", darija: "ولد" },
  { id: "word:328", en: "Girl", darija: "بنت" },
  { id: "word:329", en: "Guy", darija: "شاب / دري" },
  { id: "word:330", en: "Adult", darija: "بالغ / كبير" },
  { id: "word:331", en: "Friend", darija: "صديق / صاحب" },
  { id: "word:332", en: "Neighbor", darija: "جار" },
  { id: "word:333", en: "Guest", darija: "ضيف" },
  { id: "word:334", en: "Stranger", darija: "براني" },
  { id: "word:335", en: "Boss", darija: "شاف" },
  { id: "word:336", en: "Manager", darija: "مدير" },
  { id: "word:337", en: "Employee", darija: "خدّام" },
  { id: "word:338", en: "Student", darija: "تلميذ / طالب" },
  { id: "word:339", en: "Teacher", darija: "أستاذ" },
  { id: "word:340", en: "Doctor", darija: "طبيب" },
  { id: "word:341", en: "Patient", darija: "مريض" },
  { id: "word:342", en: "Police", darija: "بوليس" },
  { id: "word:343", en: "Driver", darija: "شوفور" },
  { id: "word:344", en: "Customer", darija: "كليان" },
  { id: "word:345", en: "Group", darija: "مجموعة" },
  { id: "word:346", en: "Team", darija: "فريق" },
  { id: "word:347", en: "Everyone", darija: "كلشي" },
  { id: "word:348", en: "Someone", darija: "شي حد" },
  { id: "word:349", en: "No one", darija: "حتى حد" },

  // --- Description & Feelings (الوصف والأحاسيس) ---
  { id: "word:350", en: "Name", darija: "سمية" },
  { id: "word:351", en: "Age", darija: "عمر" },
  { id: "word:352", en: "Old", darija: "شارف / قديم" },
  { id: "word:353", en: "Young", darija: "صغير / شباب" },
  { id: "word:354", en: "Tall", darija: "طويل" },
  { id: "word:355", en: "Short", darija: "قصير" },
  { id: "word:356", en: "Fat", darija: "غليض" },
  { id: "word:357", en: "Thin", darija: "رقيق" },
  { id: "word:358", en: "Strong", darija: "صحيح" },
  { id: "word:359", en: "Weak", darija: "ضعيف" },
  { id: "word:360", en: "Beautiful", darija: "زوينة" },
  { id: "word:361", en: "Handsome", darija: "بوكوص / زوين" },
  { id: "word:362", en: "Ugly", darija: "خايب" },
  { id: "word:363", en: "Cute", darija: "كيوت / ظريف" },
  { id: "word:364", en: "Nice", darija: "ضريف / مزيان" },
  { id: "word:365", en: "Kind", darija: "طيب" },
  { id: "word:366", en: "Mean", darija: "قبيح" },
  { id: "word:367", en: "Angry", darija: "معصب" },
  { id: "word:368", en: "Happy", darija: "فرحان" },
  { id: "word:369", en: "Sad", darija: "مقلق / حزين" },
  { id: "word:370", en: "Funny", darija: "مضحك" },
  { id: "word:371", en: "Serious", darija: "معقول" },
  { id: "word:372", en: "Smart", darija: "ذكي" },
  { id: "word:373", en: "Stupid", darija: "مكلخ" },
  { id: "word:374", en: "Rich", darija: "لاباس عليه" },
  { id: "word:375", en: "Poor", darija: "مسكين / فقير" },
  { id: "word:376", en: "Married", darija: "مزوج" },
  { id: "word:377", en: "Single", darija: "عزري / عازبة" },
  { id: "word:378", en: "Divorced", darija: "مطلق" },
  { id: "word:379", en: "Alive", darija: "حي" },
  { id: "word:380", en: "Dead", darija: "ميت" },
  
  // --- Relationship Verbs (أفعال العلاقات) ---
  { id: "word:381", en: "Born", darija: "تولد" },
  { id: "word:382", en: "Live", darija: "عاش / سكن" },
  { id: "word:383", en: "Die", darija: "مات" },
  { id: "word:384", en: "Grow", darija: "كبر" },
  { id: "word:385", en: "Marry", darija: "تزوج" },
  { id: "word:386", en: "Visit", darija: "زار" },
  { id: "word:387", en: "Meet", darija: "تلاقى" },
  { id: "word:388", en: "Call", darija: "عيط" },
  { id: "word:389", en: "Love", darija: "بغى / حب" },
  { id: "word:390", en: "Hate", darija: "كره" },
  { id: "word:391", en: "Miss", darija: "توحش" },
  { id: "word:392", en: "Kiss", darija: "باس" },
  { id: "word:393", en: "Hug", darija: "عنق" }
];

// --- THEME 4: FOOD & KITCHEN (120 Words) ---
export const theme_4_words = [
  // --- Fruits & Vegetables (الفواكه والخضر) ---
  { id: "word:401", en: "Apple", darija: "تفاحة" },
  { id: "word:402", en: "Banana", darija: "بنانة" },
  { id: "word:403", en: "Orange", darija: "ليمونة" },
  { id: "word:404", en: "Lemon", darija: "حامضة" },
  { id: "word:405", en: "Grape", darija: "عنب" },
  { id: "word:406", en: "Strawberry", darija: "فريز" },
  { id: "word:407", en: "Watermelon", darija: "دلاح" },
  { id: "word:408", en: "Date", darija: "تمرة" },
  { id: "word:409", en: "Olive", darija: "زيتونة" },
  { id: "word:410", en: "Tomato", darija: "مطيشة" },
  { id: "word:411", en: "Potato", darija: "بطاطا" },
  { id: "word:412", en: "Onion", darija: "بصلة" },
  { id: "word:413", en: "Garlic", darija: "ثومة" },
  { id: "word:414", en: "Carrot", darija: "خيزو" },
  { id: "word:415", en: "Cucumber", darija: "خيار" },
  { id: "word:416", en: "Pepper", darija: "فلفلة / إبزار" },
  { id: "word:417", en: "Mint", darija: "نعناع" },
  { id: "word:418", en: "Vegetable", darija: "خضرة" },
  { id: "word:419", en: "Fruit", darija: "فاكهة" },

  // --- Meat & Dairy (اللحوم ومشتقات الحليب) ---
  { id: "word:420", en: "Meat", darija: "لحم" },
  { id: "word:421", en: "Chicken", darija: "دجاج" },
  { id: "word:422", en: "Fish", darija: "حوت" },
  { id: "word:423", en: "Egg", darija: "بيض" },
  { id: "word:424", en: "Milk", darija: "حليب" },
  { id: "word:425", en: "Cheese", darija: "فرماج" },
  { id: "word:426", en: "Butter", darija: "زبدة" },
  { id: "word:427", en: "Yogurt", darija: "دانون / ياغورت" },
  { id: "word:428", en: "Cream", darija: "قشطة / كريمة" },

  // --- Pantry Staples (المواد الأساسية) ---
  { id: "word:429", en: "Rice", darija: "روز" },
  { id: "word:430", en: "Pasta", darija: "ليباط / مقرونية" },
  { id: "word:431", en: "Flour", darija: "طحين" },
  { id: "word:432", en: "Sugar", darija: "سكر" },
  { id: "word:433", en: "Salt", darija: "ملحة" },
  { id: "word:434", en: "Oil", darija: "زيت" },
  { id: "word:435", en: "Honey", darija: "عسل" },
  { id: "word:436", en: "Jam", darija: "كونفتير" },
  { id: "word:437", en: "Spice", darija: "عطرية" },
  { id: "word:438", en: "Soup", darija: "صوبة / حريرة" },
  { id: "word:439", en: "Salad", darija: "شلادة" },
  { id: "word:440", en: "Sandwich", darija: "سندويش" },
  { id: "word:441", en: "Pizza", darija: "بيتزا" },
  { id: "word:442", en: "Juice", darija: "عصير" },
  { id: "word:443", en: "Ice cream", darija: "لاص" },
  { id: "word:444", en: "Chocolate", darija: "شكلاط" },
  { id: "word:445", en: "Cake", darija: "كيكة / حلوة" },
  { id: "word:446", en: "Sweet", darija: "حلو" },
  { id: "word:447", en: "Sour", darija: "حامض (مذاق)" },
  { id: "word:448", en: "Salty", darija: "مالح" },
  { id: "word:449", en: "Spicy", darija: "حار" },
  { id: "word:450", en: "Delicious", darija: "بنين" },
  { id: "word:451", en: "Fresh", darija: "طري" },

  // --- Kitchen Tools & Verbs (أواني وأفعال الطبخ) ---
  { id: "word:452", en: "Knife", darija: "موس" },
  { id: "word:453", en: "Spoon", darija: "معلقة" },
  { id: "word:454", en: "Fork", darija: "فرشيطة" },
  { id: "word:455", en: "Plate", darija: "طبسيل" },
  { id: "word:456", en: "Bowl", darija: "زلافة" },
  { id: "word:457", en: "Cup", darija: "كاس" },
  { id: "word:458", en: "Glass", darija: "كاس (زجاج)" },
  { id: "word:459", en: "Bottle", darija: "قرعة" },
  { id: "word:460", en: "Pot", darija: "كاميلا / طنجرة" },
  { id: "word:461", en: "Pan", darija: "مقلاة" },
  { id: "word:462", en: "Oven", darija: "فران" },
  { id: "word:463", en: "Fridge", darija: "ثلاجة" },
  { id: "word:464", en: "Cut", darija: "قطع" },
  { id: "word:465", en: "Mix", darija: "خلط" },
  { id: "word:466", en: "Boil", darija: "سلق / غلى" },
  { id: "word:467", en: "Fry", darija: "قلى" },
  { id: "word:468", en: "Bake", darija: "طيب فالفران" },
  { id: "word:469", en: "Taste", darija: "داق" },
  { id: "word:470", en: "Smell", darija: "شم" }
];

// --- THEME 5: HOUSE & FURNITURE (100 Words) ---
export const theme_5_words = [
  // --- Parts of House (أجزاء المنزل) ---
  { id: "word:501", en: "Apartment", darija: "برطمة" },
  { id: "word:502", en: "Building", darija: "عمارة / بناية" },
  { id: "word:503", en: "Floor", darija: "أرضية / طابق" },
  { id: "word:504", en: "Wall", darija: "حيط" },
  { id: "word:505", en: "Ceiling", darija: "سقف" },
  { id: "word:506", en: "Roof", darija: "سطح" },
  { id: "word:507", en: "Stairs", darija: "دروج" },
  { id: "word:508", en: "Elevator", darija: "سانسور" },
  { id: "word:509", en: "Balcony", darija: "بالكون" },
  { id: "word:510", en: "Garden", darija: "جردة" },
  { id: "word:511", en: "Garage", darija: "كراج" },
  { id: "word:512", en: "Gate", darija: "بوابة" },
  { id: "word:513", en: "Entrance", darija: "دخلة" },
  { id: "word:514", en: "Exit", darija: "خرجة" },
  { id: "word:515", en: "Toilet", darija: "طواليت" },

  // --- Furniture & Objects (الأثاث والأشياء) ---
  { id: "word:516", en: "Table", darija: "طبلة" },
  { id: "word:517", en: "Chair", darija: "كرسي" },
  { id: "word:518", en: "Sofa", darija: "فوطوي / سداري" },
  { id: "word:519", en: "Couch", darija: "كاناپي" },
  { id: "word:520", en: "Carpet", darija: "زربية" },
  { id: "word:521", en: "Rug", darija: "تبيي" },
  { id: "word:522", en: "Curtain", darija: "خامية" },
  { id: "word:523", en: "Lamp", darija: "بولة / ليمبة" },
  { id: "word:524", en: "Light", darija: "ضو" },
  { id: "word:525", en: "Mirror", darija: "مراية" },
  { id: "word:526", en: "Picture", darija: "تصويرة" },
  { id: "word:527", en: "Clock", darija: "مكابة (حائطية)" },
  { id: "word:528", en: "Shelf", darija: "إيطاجير / رف" },
  { id: "word:529", en: "Cabinet", darija: "بلاكار" },
  { id: "word:530", en: "Drawer", darija: "مجر" },
  { id: "word:531", en: "Wardrobe", darija: "ماريو" },
  { id: "word:532", en: "Pillow", darija: "مخدة" },
  { id: "word:533", en: "Blanket", darija: "مانطة / غطا" },
  { id: "word:534", en: "Sheet", darija: "إيزار" },
  { id: "word:535", en: "Mattress", darija: "بونج / سداري" },

  // --- Appliances & Tools (الأجهزة والأدوات) ---
  { id: "word:536", en: "Machine", darija: "ماكينة" },
  { id: "word:537", en: "Washing machine", darija: "ماكينة الصابون" },
  { id: "word:538", en: "Fan", darija: "فرفارة" },
  { id: "word:539", en: "Heater", darija: "شوفاج" },
  { id: "word:540", en: "Air conditioner", darija: "كليماتيزور" },
  { id: "word:541", en: "Iron", darija: "مصلوح" },
  { id: "word:542", en: "Broom", darija: "شطابة" },
  { id: "word:543", en: "Mop", darija: "جفاف" },
  { id: "word:544", en: "Bucket", darija: "سطل" },
  { id: "word:545", en: "Trash", darija: "زبل" },
  { id: "word:546", en: "Bin", darija: "سلة المهملات" },
  { id: "word:547", en: "Switch", darija: "نڨاصة" },
  { id: "word:548", en: "Plug", darija: "بريز" },
  { id: "word:549", en: "Lock", darija: "قفل" },
  { id: "word:550", en: "Furniture", darija: "أثاث" },
  { id: "word:551", en: "Comfortable", darija: "مريح" },
  { id: "word:552", en: "Clean", darija: "نقي" },
  { id: "word:553", en: "Dirty", darija: "موسخ" },
  { id: "word:554", en: "Broken", darija: "مهرس / خاسر" },
  { id: "word:555", en: "New", darija: "جديد" }
];

// --- THEME 6: CITY & TRAVEL (100 Words) ---
export const theme_6_words = [
  // --- Places in City (أماكن المدينة) ---
  { id: "word:601", en: "City", darija: "مدينة" },
  { id: "word:602", en: "Village", darija: "عروبية / قرية" },
  { id: "word:603", en: "Center", darija: "سونطر / وسط" },
  { id: "word:604", en: "Market", darija: "سوق" },
  { id: "word:605", en: "Shop", darija: "حانوت" },
  { id: "word:606", en: "Supermarket", darija: "سوبرمارشي" },
  { id: "word:607", en: "Bakery", darija: "مخبزة" },
  { id: "word:608", en: "Pharmacy", darija: "فرماسيان" },
  { id: "word:609", en: "Hospital", darija: "سبيطار" },
  { id: "word:610", en: "Police station", darija: "كوميسارية" },
  { id: "word:611", en: "Bank", darija: "بنكة" },
  { id: "word:612", en: "Post office", darija: "بوسطة" },
  { id: "word:613", en: "Hotel", darija: "وطيل" },
  { id: "word:614", en: "Restaurant", darija: "ريسطورة" },
  { id: "word:615", en: "Cafe", darija: "قهوة (مكان)" },
  { id: "word:616", en: "Mosque", darija: "جامع" },
  { id: "word:617", en: "Park", darija: "حديقة / بارك" },
  { id: "word:618", en: "Beach", darija: "بحر / شاطئ" },
  { id: "word:619", en: "Cinema", darija: "سينما" },
  { id: "word:620", en: "Stadium", darija: "تيران" },
  { id: "word:621", en: "Airport", darija: "مطار" },
  { id: "word:622", en: "Station", darija: "محطة" },

  // --- Transport (المواصلات) ---
  { id: "word:623", en: "Train", darija: "تران" },
  { id: "word:624", en: "Plane", darija: "طيارة" },
  { id: "word:625", en: "Boat", darija: "باطو" },
  { id: "word:626", en: "Bicycle", darija: "بيكالة" },
  { id: "word:627", en: "Bike", darija: "بيكالة" },
  { id: "word:628", en: "Motorcycle", darija: "موطور" },
  { id: "word:629", en: "Truck", darija: "كاميو" },
  { id: "word:630", en: "Ticket", darija: "ورقة / تيكي" },
  { id: "word:631", en: "Passport", darija: "باسبور" },
  { id: "word:632", en: "Trip", darija: "سفرية" },
  { id: "word:633", en: "Traffic", darija: "طريق عامرة" },

  // --- Directions & Nature (الاتجاهات والطبيعة) ---
  { id: "word:634", en: "Road", darija: "طريق" },
  { id: "word:635", en: "Way", darija: "طريق / اتجاه" },
  { id: "word:636", en: "Corner", darija: "قنت / دورة" },
  { id: "word:637", en: "Bridge", darija: "قنطرة" },
  { id: "word:638", en: "Straight", darija: "نيشان" },
  { id: "word:639", en: "Back", darija: "لور" },
  { id: "word:640", en: "North", darija: "شمال" },
  { id: "word:641", en: "South", darija: "جنوب" },
  { id: "word:642", en: "East", darija: "شرق" },
  { id: "word:643", en: "West", darija: "غرب" },
  { id: "word:644", en: "Map", darija: "خريطة" },
  { id: "word:645", en: "World", darija: "عالم" },
  { id: "word:646", en: "Country", darija: "بلاد" },
  { id: "word:647", en: "Sea", darija: "بحر" },
  { id: "word:648", en: "Sky", darija: "سماء" },
  { id: "word:649", en: "Sun", darija: "شمس" },
  { id: "word:650", en: "Moon", darija: "قمر" },
  { id: "word:651", en: "Star", darija: "نجمة" },
  { id: "word:652", en: "Rain", darija: "شتا" },
  { id: "word:653", en: "Wind", darija: "برد / ريح" },
  { id: "word:654", en: "Cloud", darija: "سحاب / غيام" },
  { id: "word:655", en: "Tree", darija: "شجرة" },
  { id: "word:656", en: "Flower", darija: "وردة" },
  { id: "word:657", en: "Animal", darija: "حيوان" },
  { id: "word:658", en: "Dog", darija: "كلب" },
  { id: "word:659", en: "Cat", darija: "مشة" },
  { id: "word:660", en: "Bird", darija: "طير" }
];
// --- THEME 7: TIME, MONEY & NUMBERS (100 Words) ---
export const theme_7_words = [
  // --- Time Units (وحدات الوقت) ---
  { id: "word:701", en: "Second", darija: "ثانية" },
  { id: "word:702", en: "Minute", darija: "دقيقة" },
  { id: "word:703", en: "Hour", darija: "ساعة" },
  { id: "word:704", en: "Day", darija: "نهار / يوم" },
  { id: "word:705", en: "Week", darija: "سيمانة" },
  { id: "word:706", en: "Month", darija: "شهر" },
  { id: "word:707", en: "Year", darija: "عام" },
  { id: "word:708", en: "Century", darija: "قرن" },
  { id: "word:709", en: "Morning", darija: "صباح" },
  { id: "word:710", en: "Noon", darija: "ظهر" },
  { id: "word:711", en: "Afternoon", darija: "عشية" },
  { id: "word:712", en: "Evening", darija: "مساء" },
  { id: "word:713", en: "Night", darija: "ليل" },
  { id: "word:714", en: "Midnight", darija: "نص الليل" },
  { id: "word:715", en: "Dawn", darija: "فجر" },
  
  // --- Days of the Week (أيام الأسبوع) ---
  { id: "word:716", en: "Monday", darija: "الاثنين" },
  { id: "word:717", en: "Tuesday", darija: "الثلاثاء" },
  { id: "word:718", en: "Wednesday", darija: "الأربعاء" },
  { id: "word:719", en: "Thursday", darija: "الخميس" },
  { id: "word:720", en: "Friday", darija: "الجمعة" },
  { id: "word:721", en: "Saturday", darija: "السبت" },
  { id: "word:722", en: "Sunday", darija: "الأحد" },

  // --- Months (الشهور) ---
  { id: "word:723", en: "January", darija: "شهر 1 (يناير)" },
  { id: "word:724", en: "February", darija: "شهر 2 (فبراير)" },
  { id: "word:725", en: "March", darija: "شهر 3 (مارس)" },
  { id: "word:726", en: "April", darija: "شهر 4 (أبريل)" },
  { id: "word:727", en: "May", darija: "شهر 5 (ماي)" },
  { id: "word:728", en: "June", darija: "شهر 6 (يونيو)" },
  { id: "word:729", en: "July", darija: "شهر 7 (يوليوز)" },
  { id: "word:730", en: "August", darija: "شهر 8 (غشت)" },
  { id: "word:731", en: "September", darija: "شهر 9 (شتنبر)" },
  { id: "word:732", en: "October", darija: "شهر 10 (أكتوبر)" },
  { id: "word:733", en: "November", darija: "شهر 11 (نونبر)" },
  { id: "word:734", en: "December", darija: "شهر 12 (دجنبر)" },

  // --- Numbers (الأرقام) ---
  { id: "word:735", en: "Eleven", darija: "حضاش (11)" },
  { id: "word:736", en: "Twelve", darija: "طناش (12)" },
  { id: "word:737", en: "Thirteen", darija: "ثلطاش (13)" },
  { id: "word:738", en: "Fourteen", darija: "ربعطاش (14)" },
  { id: "word:739", en: "Fifteen", darija: "خمسطاش (15)" },
  { id: "word:740", en: "Twenty", darija: "عشرين (20)" },
  { id: "word:741", en: "Thirty", darija: "ثلاثين (30)" },
  { id: "word:742", en: "Forty", darija: "ربعين (40)" },
  { id: "word:743", en: "Fifty", darija: "خمسين (50)" },
  { id: "word:744", en: "Sixty", darija: "ستين (60)" },
  { id: "word:745", en: "Seventy", darija: "سبعين (70)" },
  { id: "word:746", en: "Eighty", darija: "ثمانين (80)" },
  { id: "word:747", en: "Ninety", darija: "تسعين (90)" },
  { id: "word:748", en: "Thousand", darija: "ألف (1000)" },
  { id: "word:749", en: "Million", darija: "مليون" },
  { id: "word:750", en: "Half", darija: "نص" },
  { id: "word:751", en: "Quarter", darija: "ربع" },

  // --- Money & Business (الفلوس والتجارة) ---
  { id: "word:752", en: "Money", darija: "فلوس" },
  { id: "word:753", en: "Cash", darija: "صرف / كاش" },
  { id: "word:754", en: "Card", darija: "كارطة" },
  { id: "word:755", en: "Price", darija: "ثمن" },
  { id: "word:756", en: "Cost", darija: "تكلفة" },
  { id: "word:757", en: "Cheap", darija: "رخيص" },
  { id: "word:758", en: "Expensive", darija: "غالي" },
  { id: "word:759", en: "Sale", darija: "صولد / تخفيض" },
  { id: "word:760", en: "Bill", darija: "فاكتورة / حساب" },
  { id: "word:761", en: "Wallet", darija: "بسطام" },
  { id: "word:762", en: "Spend", darija: "خسر (فلوس)" },
  { id: "word:763", en: "Save", darija: "خبى / وفر" },
  { id: "word:764", en: "Borrow", darija: "تسلف (من عند)" },
  { id: "word:765", en: "Lend", darija: "سلف (لـ)" },
  { id: "word:766", en: "Bank", darija: "بنكة" },
  { id: "word:767", en: "Rich", darija: "لاباس عليه" },
  { id: "word:768", en: "Poor", darija: "فقير / مسكين" },
  { id: "word:769", en: "Free", darija: "فابور" },
  { id: "word:770", en: "Total", darija: "مجموع" }
];

// --- THEME 8: CLOTHES & SHOPPING (90 Words) ---
export const theme_8_words = [
  // --- Clothing Items (الملابس) ---
  { id: "word:801", en: "Clothes", darija: "حوايج" },
  { id: "word:802", en: "Shirt", darija: "قميجة" },
  { id: "word:803", en: "T-shirt", darija: "تيشورت" },
  { id: "word:804", en: "Pants", darija: "سروال" },
  { id: "word:805", en: "Jeans", darija: "دجين" },
  { id: "word:806", en: "Shorts", darija: "شورط" },
  { id: "word:807", en: "Dress", darija: "كسوة" },
  { id: "word:808", en: "Skirt", darija: "صاية" },
  { id: "word:809", en: "Jacket", darija: "جاكيطة" },
  { id: "word:810", en: "Coat", darija: "مونطو" },
  { id: "word:811", en: "Sweater", darija: "تريكو" },
  { id: "word:812", en: "Suit", darija: "كوستيم" },
  { id: "word:813", en: "Pajamas", darija: "بيجامة" },
  { id: "word:814", en: "Underwear", darija: "ملابس داخلية" },
  { id: "word:815", en: "Socks", darija: "تقاشر" },
  { id: "word:816", en: "Shoes", darija: "صباط" },
  { id: "word:817", en: "Sneakers", darija: "سبيدرية" },
  { id: "word:818", en: "Sandals", darija: "صندالة" },
  { id: "word:819", en: "Boots", darija: "بوط" },
  { id: "word:820", en: "Hat", darija: "طربية / كاسكيطة" },
  { id: "word:821", en: "Scarf", darija: "شال / كاشكول" },
  { id: "word:822", en: "Gloves", darija: "ليكات" },
  { id: "word:823", en: "Belt", darija: "سمطة" },
  { id: "word:824", en: "Tie", darija: "كرافاطة" },
  { id: "word:825", en: "Hijab", darija: "زيف / حجاب" },
  { id: "word:826", en: "Djellaba", darija: "جلابة" },
  { id: "word:827", en: "Caftan", darija: "قفطان" },

  // --- Accessories & Details (أكسسوارات وتفاصيل) ---
  { id: "word:828", en: "Glasses", darija: "نظاظر" },
  { id: "word:829", en: "Sunglasses", darija: "نظاظر الشمس" },
  { id: "word:830", en: "Watch", darija: "ماكانة" },
  { id: "word:831", en: "Ring", darija: "خاتم" },
  { id: "word:832", en: "Necklace", darija: "سنسلة" },
  { id: "word:833", en: "Earrings", darija: "حلقات" },
  { id: "word:834", en: "Bag", darija: "صاك / شكارة" },
  { id: "word:835", en: "Umbrella", darija: "مظلة" },
  { id: "word:836", en: "Pocket", darija: "جيب" },
  { id: "word:837", en: "Button", darija: "صدفة" },
  { id: "word:838", en: "Zipper", darija: "سلسلة" },
  { id: "word:839", en: "Size", darija: "قياس / طاي" },
  { id: "word:840", en: "Large", darija: "كبير (L)" },
  { id: "word:841", en: "Medium", darija: "موايان (M)" },
  { id: "word:842", en: "Small", darija: "صغير (S)" },
  { id: "word:843", en: "Tight", darija: "مزيّر" },
  { id: "word:844", en: "Loose", darija: "عريض" },
  { id: "word:845", en: "Long", darija: "طويل" },
  { id: "word:846", en: "Short", darija: "قصير" },

  // --- Colors (الألوان) ---
  { id: "word:847", en: "Color", darija: "لون" },
  { id: "word:848", en: "Red", darija: "حمر" },
  { id: "word:849", en: "Blue", darija: "زرق" },
  { id: "word:850", en: "Green", darija: "خضر" },
  { id: "word:851", en: "Yellow", darija: "صفر" },
  { id: "word:852", en: "Black", darija: "كحل" },
  { id: "word:853", en: "White", darija: "بيض" },
  { id: "word:854", en: "Orange", darija: "ليموني" },
  { id: "word:855", en: "Pink", darija: "وردي" },
  { id: "word:856", en: "Purple", darija: "موف" },
  { id: "word:857", en: "Brown", darija: "قهوي" },
  { id: "word:858", en: "Grey", darija: "رمادي" },
  { id: "word:859", en: "Gold", darija: "ذهبي" },
  { id: "word:860", en: "Silver", darija: "فضي" },
  { id: "word:861", en: "Light", darija: "فاتح" },
  { id: "word:862", en: "Dark", darija: "غامق" },

  // --- Shopping Verbs (أفعال التسوق) ---
  { id: "word:863", en: "Wear", darija: "لبس" },
  { id: "word:864", en: "Try on", darija: "قيس" },
  { id: "word:865", en: "Fit", darija: "جا قدو" },
  { id: "word:866", en: "Buy", darija: "شرا" },
  { id: "word:867", en: "Sell", darija: "باع" },
  { id: "word:868", en: "Pay", darija: "خلص" },
  { id: "word:869", en: "Choose", darija: "ختار" },
  { id: "word:870", en: "Look for", darija: "قلب على" }
];

// --- THEME 9: HEALTH & BODY (80 Words) ---
export const theme_9_words = [
  // --- Body Parts (أعضاء الجسم) ---
  { id: "word:901", en: "Body", darija: "جسم / دات" },
  { id: "word:902", en: "Head", darija: "راس" },
  { id: "word:903", en: "Hair", darija: "شعر" },
  { id: "word:904", en: "Face", darija: "وجه" },
  { id: "word:905", en: "Eye", darija: "عين" },
  { id: "word:906", en: "Ear", darija: "ودن" },
  { id: "word:907", en: "Nose", darija: "نيف" },
  { id: "word:908", en: "Mouth", darija: "فم" },
  { id: "word:909", en: "Tooth", darija: "سنة" },
  { id: "word:910", en: "Teeth", darija: "سنان" },
  { id: "word:911", en: "Tongue", darija: "لسان" },
  { id: "word:912", en: "Neck", darija: "عنق" },
  { id: "word:913", en: "Shoulder", darija: "كتف" },
  { id: "word:914", en: "Arm", darija: "دراع" },
  { id: "word:915", en: "Hand", darija: "يد" },
  { id: "word:916", en: "Finger", darija: "صبع" },
  { id: "word:917", en: "Chest", darija: "صدر" },
  { id: "word:918", en: "Stomach", darija: "كرش / معدة" },
  { id: "word:919", en: "Back", darija: "ظهر" },
  { id: "word:920", en: "Leg", darija: "رجل" },
  { id: "word:921", en: "Knee", darija: "ركبة" },
  { id: "word:922", en: "Foot", darija: "قدم" },
  { id: "word:923", en: "Skin", darija: "جلد" },
  { id: "word:924", en: "Blood", darija: "دم" },
  { id: "word:925", en: "Heart", darija: "قلب" },
  { id: "word:926", en: "Brain", darija: "مخ / دماغ" },

  // --- Health & Sickness (الصحة والمرض) ---
  { id: "word:927", en: "Health", darija: "صحة" },
  { id: "word:928", en: "Sick", darija: "مريض" },
  { id: "word:929", en: "Pain", darija: "حريق / ألم" },
  { id: "word:930", en: "Fever", darija: "سخانة" },
  { id: "word:931", en: "Cold", darija: "رواح / برد" },
  { id: "word:932", en: "Cough", darija: "كحبة" },
  { id: "word:933", en: "Headache", darija: "حريق الراس" },
  { id: "word:934", en: "Medicine", darija: "دواء" },
  { id: "word:935", en: "Pill", darija: "كينة" },
  { id: "word:936", en: "Doctor", darija: "طبيب" },
  { id: "word:937", en: "Nurse", darija: "فرملية" },
  { id: "word:938", en: "Hospital", darija: "سبيطار" },
  { id: "word:939", en: "Pharmacy", darija: "فرماسيان" },
  { id: "word:940", en: "Ambulance", darija: "إسعاف" },
  { id: "word:941", en: "Appointment", darija: "رونديفو" },
  { id: "word:942", en: "Emergency", darija: "مستعجلات" },
  { id: "word:943", en: "Tired", darija: "عيان" },
  { id: "word:944", en: "Healthy", darija: "صحي" },
  { id: "word:945", en: "Strong", darija: "صحيح" },
  { id: "word:946", en: "Weak", darija: "ضعيف" },
  { id: "word:947", en: "Pregnancy", darija: "حمالة" },
  { id: "word:948", en: "Sleep", darija: "نعاس" },
  { id: "word:949", en: "Rest", darija: "راحة" },
  { id: "word:950", en: "Feel", darija: "حس" }
];

// --- THEME 10: NATURE, FEELINGS & ABSTRACT (80 Words) ---
export const theme_10_words = [
  // --- Nature & Weather (الطبيعة والجو) ---
  { id: "word:1001", en: "Weather", darija: "جو" },
  { id: "word:1002", en: "Sun", darija: "شمس" },
  { id: "word:1003", en: "Moon", darija: "قمر" },
  { id: "word:1004", en: "Star", darija: "نجمة" },
  { id: "word:1005", en: "Sky", darija: "سماء" },
  { id: "word:1006", en: "Cloud", darija: "سحاب" },
  { id: "word:1007", en: "Rain", darija: "شتا" },
  { id: "word:1008", en: "Snow", darija: "ثلج" },
  { id: "word:1009", en: "Wind", darija: "برد / ريح" },
  { id: "word:1010", en: "Hot", darija: "سخون" },
  { id: "word:1011", en: "Cold", darija: "بارد" },
  { id: "word:1012", en: "Sea", darija: "بحر" },
  { id: "word:1013", en: "Mountain", darija: "جبل" },
  { id: "word:1014", en: "River", darija: "واد" },
  { id: "word:1015", en: "Tree", darija: "شجرة" },
  { id: "word:1016", en: "Flower", darija: "وردة" },
  { id: "word:1017", en: "Grass", darija: "ربيع" },
  { id: "word:1018", en: "Sand", darija: "رملة" },
  { id: "word:1019", en: "Fire", darija: "عافية" },
  { id: "word:1020", en: "Water", darija: "ماء" },
  { id: "word:1021", en: "Air", darija: "هواء" },
  { id: "word:1022", en: "Light", darija: "ضو" },
  { id: "word:1023", en: "Dark", darija: "ظلام" },

  // --- Feelings & Adjectives (أحاسيس وصفات) ---
  { id: "word:1024", en: "Happy", darija: "فرحان" },
  { id: "word:1025", en: "Sad", darija: "مقلق / حزين" },
  { id: "word:1026", en: "Angry", darija: "معصب" },
  { id: "word:1027", en: "Scared", darija: "خايف" },
  { id: "word:1028", en: "Surprised", darija: "مصدوم" },
  { id: "word:1029", en: "Bored", darija: "مملل" },
  { id: "word:1030", en: "Hungry", darija: "جيعان" },
  { id: "word:1031", en: "Thirsty", darija: "عطشان" },
  { id: "word:1032", en: "Full", darija: "شبعان" },
  { id: "word:1033", en: "Tired", darija: "عيان" },
  { id: "word:1034", en: "Good", darija: "مزيان" },
  { id: "word:1035", en: "Bad", darija: "خايب" },
  { id: "word:1036", en: "Better", darija: "حسن" },
  { id: "word:1037", en: "Worse", darija: "كفس" },
  { id: "word:1038", en: "Important", darija: "مهم" },
  { id: "word:1039", en: "Easy", darija: "ساهل" },
  { id: "word:1040", en: "Hard", darija: "صعيب" },
  { id: "word:1041", en: "Clean", darija: "نقي" },
  { id: "word:1042", en: "Dirty", darija: "موسخ" },
  { id: "word:1043", en: "Right", darija: "صحيح" },
  { id: "word:1044", en: "Wrong", darija: "غلط" },
  { id: "word:1045", en: "Same", darija: "نفس الحاجة" },
  { id: "word:1046", en: "Different", darija: "مختلف" },
  { id: "word:1047", en: "True", darija: "حقيقة" },
  { id: "word:1048", en: "Lie", darija: "كدوب" },
  
  // --- Useful Verbs (أفعال إضافية) ---
  { id: "word:1049", en: "Think", darija: "فكر" },
  { id: "word:1050", en: "Remember", darija: "عقل" },
  { id: "word:1051", en: "Forget", darija: "نسى" },
  { id: "word:1052", en: "Find", darija: "لقى" },
  { id: "word:1053", en: "Lose", darija: "ودر" },
  { id: "word:1054", en: "Start", darija: "بدا" },
  { id: "word:1055", en: "Stop", darija: "حبس" },
  { id: "word:1056", en: "Open", darija: "حل" },
  { id: "word:1057", en: "Close", darija: "سد" },
  { id: "word:1058", en: "Ask", darija: "سول" },
  { id: "word:1059", en: "Answer", darija: "جاوب" },
  { id: "word:1060", en: "Change", darija: "بدل" }
];